### ISSUE TITLE
Task_wdt: Task watchdog got triggered!why?

### ISSUE THREAD

**Issue by caacnet** [atomic14/esp32-laser-show#3]
E (14325) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (14325) task_wdt:  - IDLE (CPU 0)
E (14325) task_wdt: Tasks currently running:
E (14325) task_wdt: CPU 0: main
E (14325) task_wdt: CPU 1: IDLE
E (14325) task_wdt: Print CPU 0 (current core) backtrace

Backtrace:0x400E0DC4:0x3FFB06F0 0x40082EA5:0x3FFB0710 0x400D19C4:0x3FFB5FC0 0x400D11C1:0x3FFB6020 0x400D12D3:0x3FFB6040 0x400D166A:0x3FFB60C0 0x400EF284:0x3FFB6100 0x40089851:0x3FFB6120
  #0  0x400E0DC4:0x3FFB06F0 in task_wdt_isr at C:\Users\Administrator\.platformio\packages\framework-espidf\components\esp_common\src/task_wdt.c:189    
  #1  0x40082EA5:0x3FFB0710 in _xt_lowint1 at C:\Users\Administrator\.platformio\packages\framework-espidf\components\freertos\port\xtensa/xtensa_vectors.S:1105
  #2  0x400D19C4:0x3FFB5FC0 in inflate at lib/zlib/inflate.c:656
  #3  0x400D11C1:0x3FFB6020 in GZipFile::read(unsigned char*, unsigned int) at src/GZipFile.cpp:42
  #4  0x400D12D3:0x3FFB6040 in ILDAFile::read(char const*) at src/ILDAFile.cpp:47
  #5  0x400D166A:0x3FFB60C0 in app_main at src/main.cpp:63 (discriminator 2)
  #6  0x400EF284:0x3FFB6100 in main_task at C:\Users\Administrator\.platformio\packages\framework-espidf\components\freertos\port/port_common.c:133 (discriminator 2)
  #7  0x40089851:0x3FFB6120 in vPortTaskWrapper at C:\Users\Administrator\.platformio\packages\framework-espidf\components\freertos\port\xtensa/port.c:168

E (14325) task_wdt: Print CPU 1 backtrace

**Comment by cgreening** [comment]
Can you try the latest code - this should hopefully be fixed by this: c5ac940737fc7e6614a4cb0b57abc67bce780d05
