### ISSUE TITLE
what changes needed to run the Code on ESP32-WROOM-32 az-delivery-devkit-v4

### ISSUE THREAD

**Issue by therealwendler** [atomic14/esp32-laser-show#5]
Hello Community,

i want to run the Code on an ESP32-WROOM-32 device wich has not any type of PSRAM. What changes should i do in the Configuration platform.ini 

i added build_flags = -DBOARD_HAS_PSRAM=0 then it starts reading the idl.gz files.

and i only uploaded one idl.gz to spiffs

Actually it reads the uploaded .gz files infinite and then the watchdog timer says that CPU1 is idle and trigged the wdt.

[error.txt](https://github.com/atomic14/esp32-laser-show/files/10316634/error.txt)

THX for your help

**Comment by cgreening** [comment]
I don't think it will work without PSRAM.
