### ISSUE TITLE
I cant build

### ISSUE THREAD

**Issue by giulianomeini** [atomic14/esp32-laser-show#6]
I get this: "src/SPIRenderer.cpp:82:3: error: 'timer_spinlock_give' was not declared in this scope" 
Where is timer_spinlock_give?
Thanks
Giuliano

**Comment by cgreening** [comment]
Ok, so looks like that function call has been removed in the latest version of the idf.

https://esp32.com/viewtopic.php?t=29726

I've pinned the version in platform io to an older version. Reading the forum thread above a proper fix looks pretty complicated...
